services:
  db:
    ports:
      - "5432:5432"

  seed:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proyecto_taller_seed
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "pnpm run db:seed"
    networks:
      - app

  backend:
    environment:
      NODE_ENV: development
      SWAGGER_ENABLED: "true"
      ALLOWED_ORIGIN: "http://localhost:4200,http://localhost:8081,http://localhost"

  frontend:
    ports:
      - "4200:80"

  marketing:
    ports:
      - "8081:80"

  nginx:
    ports:
      - "80:80"