services:
  backend:
    environment:
      NODE_ENV: production
      SWAGGER_ENABLED: ${SWAGGER_ENABLED:-false}
      ALLOWED_ORIGIN: "https://compex.bitwaise.com,https://me.compex.bitwaise.com"

  frontend:
    expose:
      - "80"

  marketing:
    expose:
      - "80"

  nginx:
    ports:
      - "80:80"
      - "443:443"